name: CD

on:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build from TypeScript
      run: npm run build

    - name: Move LICENSE and README to root
      run: |
        cp .github/LICENSE LICENSE
        cp .github/README.md README.md

  publish-package:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Publish package
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to GitHub Package Registry
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm config set @plushveil:registry https://npm.pkg.github.com
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
